wandb_version: 1

Model:
  desc: null
  value: v19
Machine:
  desc: null
  value: Main
policy:
  desc: null
  value: MlpPolicy
model_save_name:
  desc: null
  value: '1700724933'
_wandb:
  desc: null
  value:
    code_path: code/order-action/trainppo.py
    python_version: 3.10.10
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700724938.546378
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.10
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
